### ISSUE TITLE
Race condition in parsing the dns message

### ISSUE THREAD

**Issue by lordzomat** [stephbu/csharp-dns-server#23]
I detected a race condition in your parsing logic of the dns messages.

You pass the `SocketAsyncEventArgs` object directly to the method `OnRequest` which will be processed in a new thread. 
https://github.com/stephbu/csharp-dns-server/blob/5c01d53ae13d6a4fff01d4c13cf4a56bdc046916/Dns/UdpListener.cs#L37
https://github.com/stephbu/csharp-dns-server/blob/5c01d53ae13d6a4fff01d4c13cf4a56bdc046916/Dns/UdpListener.cs#L54

Right before or during the processing happens another DNS message could be received which will change the content of the buffer inside the `SocketAsyncEventArgs` so the already running thread parsing the first message will likely see parts of the new message if it's not done yet.

This happened in my case, where my linux device send two requests in parallel one "IN A" and "IN AAAA". The first message received was the "IN A" request but right before the parser came to the point to read the type of the request the second message changed the buffer and the type was read as "AAAA".

You should consider to copy the content of the received data to a new buffer and pass that to your parser for example like so:
```
if (OnRequest != null)
{
	var buffer = new byte[bytesRead];
	Buffer.BlockCopy(args.Buffer, 0, buffer, 0, buffer.Length);
	var process = Task.Run(() => OnRequest(args, buffer));
}
```

This ensures that each thread has it's own data and that `args.Buffer` is not accessed in parallel from multiple threads at the same time.

Regardless of this issue, your DNS server helped my to diagnose a little issue on my linux device. I used it to check which exact requests are send. Thanks for the great work!

**Comment by stephbu** [comment]
Neat work - I'm accepting PR's, otherwise if I get time I'll fix it at the weekend.  Appreciate the find, and feedback too.  Glad it was helpful!

**Comment by lordzomat** [comment]
If I there is time for it I will do a PR likely at the weekend.
